name: Deploy cloud workflow
on: [push]
jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: ls
      run: ls; echo $PWD;
    - name: Use gcloud CLI
      working-directory: .
      run: gcloud workflows deploy fromgithub --location=us-central1 --source=myFirstWorkflow.yaml --project ${{ secrets.GCP_PROJECT_ID }} --service-account=my-wf-service-account-11@serverless-com-demo.iam.gserviceaccount.com
      # - name: Use gcloud CLI
      # run: gcloud info
    # - name: Activate SA
    #   run: gcloud auth activate-service-account