name: Deploy cloud workflow
on: [push]
jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Use gcloud CLI
      run: gcloud workflows deploy myFirstWorkflow --location=us-central1 --source=myFirstWorkflow.yaml --project ${{ secrets.GCP_PROJECT_ID }}